detectors:
  IrresponsibleModule:
    enabled: false

  DuplicateMethodCall:
    enabled: false

  UtilityFunction:
    public_methods_only: true

  InstanceVariableAssumption:
    enabled: false

exclude_paths:
    - db
    - config
