detectors:
  IrresponsibleModule:
    enabled: false
    exclude:
      - db/
      - config/
  DuplicateMethodCall:
    enabled: false
    exclude:
      - db/
      - config/
  UtilityFunction:
    public_methods_only: true
    exclude:
      - db/
      - config/
  FeatureEnvy:
    enabled: false
    exclude:
      - db/
      - config/
  TooManyStatements:
    enabled: false
    exclude:
      - db/
      - config/
  UncommunicativeVariableName:
    enabled: false
    exclude:
      - db/
      - config/
  InstanceVariableAssumption:
    enabled: false
    exclude:
      - db/
      - config/
