detectors:
  IrresponsibleModule:
    enabled: false
  DuplicateMethodCall:
    enabled: false
  UtilityFunction:
    public_methods_only: true

directories:
  "nicher/db/":
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
    IrresponsibleModule:
      enabled: false
  "nicher/config/":
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
    IrresponsibleModule:
      enabled: false

exclude_paths:
  - db/
  - db/migrate
  - config/
