detectors:
  IrresponsibleModule:
    enabled: false
  DuplicateMethodCall:
    enabled: false
  UtilityFunction:
    public_methods_only: true

directories:
  'db':
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
    IrresponsibleModule:
      enabled: false
  'config':
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
    IrresponsibleModule:
      enabled: false
