development:
  adapter: postgresql
  encoding: unicode
  database: nicher_development
  pool: 5
  username: nicher
  password: nicher12345678

test:
  adapter: postgresql
  encoding: unicode
  database: nicher_test
  pool: 5
  username: nicher
  password: nicher12345678

